# Generated by Django 2.2.16 on 2021-04-10 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waterproof_intake', '0001_initial'),
        ('waterproof_treatment_plants', '0001_initial'),
        ('waterproof_study_cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='wbPtap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('function_graph', models.IntegerField(verbose_name='Graph Id Function')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('awy', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('q_l_s', models.FloatField(blank=True, default=None, null=True, verbose_name='Qls')),
                ('cn_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='Cn')),
                ('cp_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CpMgl')),
                ('csed_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CsedMgL')),
                ('wn_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg')),
                ('wp_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpKg')),
                ('wsed_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon')),
                ('wn_ret_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnRetKg')),
                ('wp_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WpRetTon')),
                ('wsed_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedRetTon')),
                ('function_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Function')),
                ('studycase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='wbIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('water_intake', models.IntegerField(verbose_name='Water intake id')),
                ('element', models.IntegerField(verbose_name='Element Id')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('awy', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('q_l_s', models.FloatField(blank=True, default=None, null=True, verbose_name='Qls')),
                ('cn_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='Cn')),
                ('cp_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CpMgl')),
                ('csed_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CsedMgL')),
                ('wn_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg')),
                ('wp_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpKg')),
                ('wsed_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon')),
                ('wn_ret_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnRetKg')),
                ('wp_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WpRetTon')),
                ('wsed_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedRetTon')),
                ('studycase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='investIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Time')),
                ('type', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('awy', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('wn_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg')),
                ('wp_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpKg')),
                ('wsed_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon')),
                ('bf_m3', models.FloatField(blank=True, default=None, null=True, verbose_name='BfM3')),
                ('wc_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WcTon')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake')),
                ('study_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='calculateCostFunctionPtap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('function_graph', models.IntegerField(verbose_name='Graph Id Function')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('value_calculate', models.FloatField(blank=True, default=0, null=True, verbose_name='Value calculate')),
                ('cost_function', models.IntegerField(verbose_name='Graph Id Function')),
                ('currency_function', models.CharField(blank=True, max_length=4, null=True)),
                ('date_excution', models.DateTimeField(blank=True, null=True)),
                ('function_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Function')),
                ('study_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='calculateCostFunctionIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('water_intake', models.IntegerField(verbose_name='Water intake id')),
                ('element', models.IntegerField(verbose_name='Element Id')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('value_calculate', models.FloatField(blank=True, default=0, null=True, verbose_name='Value calculate')),
                ('cost_function', models.IntegerField(verbose_name='Graph Id Function')),
                ('currency_function', models.CharField(blank=True, max_length=4, null=True)),
                ('date_excution', models.DateTimeField(blank=True, null=True)),
                ('study_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
