# Generated by Django 2.2.16 on 2021-04-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calculateCostFunctionIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('water_intake', models.IntegerField(verbose_name='Water intake id')),
                ('element', models.IntegerField(verbose_name='Element Id')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('value_calculate', models.FloatField(blank=True, default=0, null=True, verbose_name='Value calculate')),
                ('cost_function', models.IntegerField(verbose_name='Graph Id Function')),
                ('currency_function', models.CharField(blank=True, max_length=4, null=True)),
                ('date_excution', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='calculateCostFunctionPtap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('function_graph', models.IntegerField(verbose_name='Graph Id Function')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('value_calculate', models.FloatField(blank=True, default=0, null=True, verbose_name='Value calculate')),
                ('cost_function', models.IntegerField(verbose_name='Graph Id Function')),
                ('currency_function', models.CharField(blank=True, max_length=4, null=True)),
                ('date_excution', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='wbIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('water_intake', models.IntegerField(verbose_name='Water intake id')),
                ('element', models.IntegerField(verbose_name='Element Id')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('awy', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('q_l_s', models.FloatField(blank=True, default=None, null=True, verbose_name='Qls')),
                ('cn_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='Cn')),
                ('cp_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CpMgl')),
                ('csed_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CsedMgL')),
                ('wn_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg')),
                ('wp_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpKg')),
                ('wsed_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon')),
                ('wn_ret_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnRetKg')),
                ('wp_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WpRetTon')),
                ('wsed_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedRetTon')),
            ],
        ),
        migrations.CreateModel(
            name='wbPtap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('function_graph', models.IntegerField(verbose_name='Graph Id Function')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('awy', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('q_l_s', models.FloatField(blank=True, default=None, null=True, verbose_name='Qls')),
                ('cn_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='Cn')),
                ('cp_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CpMgl')),
                ('csed_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CsedMgL')),
                ('wn_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg')),
                ('wp_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpKg')),
                ('wsed_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon')),
                ('wn_ret_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnRetKg')),
                ('wp_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WpRetTon')),
                ('wsed_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedRetTon')),
            ],
        ),
    ]
