# Generated by Django 2.2.16 on 2021-09-17 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_study_cases', '__first__'),
        ('waterproof_treatment_plants', '__first__'),
        ('waterproof_intake', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportsVpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=4)),
                ('implementation', models.FloatField()),
                ('maintenance', models.FloatField()),
                ('oportunity', models.FloatField()),
                ('transaction', models.FloatField()),
                ('platform', models.FloatField()),
                ('benefit', models.FloatField()),
                ('total', models.FloatField()),
                ('date_execution', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waterproof_reports_vpn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='resultRoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=4, null=True)),
                ('roi_without_discount', models.FloatField()),
                ('roi_minimum', models.FloatField()),
                ('roi_maximum', models.FloatField()),
                ('roi_medium', models.FloatField()),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waterproof_report_result_roi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('study_case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
            ],
        ),
        migrations.CreateModel(
            name='wbPtap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('element_id', models.IntegerField(default=-1, verbose_name='Element Id')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('awy', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('cn_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='Cn')),
                ('cp_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CpMgl')),
                ('csed_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CsedMgL')),
                ('wn_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg')),
                ('wp_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpKg')),
                ('wsed_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon')),
                ('wn_ret_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnRetKg')),
                ('wp_ret_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpRetKg')),
                ('wsed_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedRetTon')),
                ('ptap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Header')),
                ('studycase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='wbIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('water_intake', models.IntegerField(verbose_name='Water intake id')),
                ('element', models.IntegerField(verbose_name='Element Id')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('awy', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('q_l_s', models.FloatField(blank=True, default=None, null=True, verbose_name='Qls')),
                ('cn_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='Cn')),
                ('cp_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CpMgl')),
                ('csed_mg_l', models.FloatField(blank=True, default=None, null=True, verbose_name='CsedMgL')),
                ('wn_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg')),
                ('wp_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpKg')),
                ('wsed_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon')),
                ('wn_ret_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnRetKg')),
                ('wp_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WpRetTon')),
                ('wsed_ret_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedRetTon')),
                ('studycase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rios_ipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('sbn', models.CharField(max_length=100)),
                ('actual_spent', models.FloatField(blank=True, default=None, null=True, verbose_name='Actual spent')),
                ('total_budget', models.FloatField(blank=True, default=None, null=True, verbose_name='Total budget')),
                ('area_converted_ha', models.FloatField(blank=True, default=None, null=True, verbose_name='Area converted ha')),
                ('execution_date', models.DateField()),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake')),
                ('study_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='investIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='Time')),
                ('type', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('awy', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('wn_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg')),
                ('wp_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpKg')),
                ('wsed_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon')),
                ('bf_m3', models.FloatField(blank=True, default=None, null=True, verbose_name='BfM3')),
                ('wc_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WcTon')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake')),
                ('study_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='invest_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('type', models.CharField(max_length=100)),
                ('awy', models.FloatField(blank=True, default=None, null=True, verbose_name='Awy')),
                ('wn_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WnKg')),
                ('wp_kg', models.FloatField(blank=True, default=None, null=True, verbose_name='WpKg')),
                ('wsed_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WsedTon')),
                ('bf_m3', models.FloatField(blank=True, default=None, null=True, verbose_name='BfM3')),
                ('wc_ton', models.FloatField(blank=True, default=None, null=True, verbose_name='WcTon')),
                ('execution_date', models.DateField()),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.Intake')),
                ('study_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='calculateCostFunctionPtap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=10)),
                ('function_graph', models.IntegerField(verbose_name='Graph Id Function')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('value_calculate', models.FloatField(blank=True, default=0, null=True, verbose_name='Value calculate')),
                ('cost_function', models.IntegerField(verbose_name='Graph Id Function')),
                ('currency_function', models.CharField(blank=True, max_length=4, null=True)),
                ('date_excution', models.DateTimeField(blank=True, null=True)),
                ('study_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
