# Generated by Django 2.2.16 on 2021-09-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='link_log',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
