# Generated by Django 2.2.16 on 2021-04-03 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_reports', '0001_initial'),
        ('waterproof_treatment_plants', '0001_initial'),
        ('waterproof_study_cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbptap',
            name='function_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Function'),
        ),
        migrations.AddField(
            model_name='wbptap',
            name='studycase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases'),
        ),
        migrations.AddField(
            model_name='wbptap',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wbintake',
            name='studycase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases'),
        ),
        migrations.AddField(
            model_name='wbintake',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calculatecostfunctionptap',
            name='function_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Function'),
        ),
        migrations.AddField(
            model_name='calculatecostfunctionptap',
            name='study_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases'),
        ),
        migrations.AddField(
            model_name='calculatecostfunctionptap',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calculatecostfunctionintake',
            name='study_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases'),
        ),
        migrations.AddField(
            model_name='calculatecostfunctionintake',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
