# Generated by Django 2.2.16 on 2021-05-05 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_treatment_plants', '0001_initial'),
        ('waterproof_reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbptap',
            name='function_graph',
        ),
        migrations.RemoveField(
            model_name='wbptap',
            name='function_plant',
        ),
        migrations.RemoveField(
            model_name='wbptap',
            name='q_l_s',
        ),
        migrations.RemoveField(
            model_name='wbptap',
            name='wp_ret_ton',
        ),
        migrations.AddField(
            model_name='wbptap',
            name='element_id',
            field=models.IntegerField(default=-1, verbose_name='Element Id'),
        ),
        migrations.AddField(
            model_name='wbptap',
            name='ptap_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Header'),
        ),
        migrations.AddField(
            model_name='wbptap',
            name='wp_ret_kg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='WpRetKg'),
        ),
    ]
