# Generated by Django 2.2.16 on 2021-05-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_reports', '0002_auto_20210504_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wbptap',
            old_name='ptap_id',
            new_name='ptap',
        ),
    ]
