# Generated by Django 2.2.16 on 2021-08-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_reports', '0004_invest_results_rios_ipa'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportsVpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=4)),
                ('implementation', models.FloatField()),
                ('maintenance', models.FloatField()),
                ('oportunity', models.FloatField()),
                ('transaction', models.FloatField()),
                ('platform', models.FloatField()),
                ('benefit', models.FloatField()),
                ('total', models.FloatField()),
                ('date_execution', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waterproof_reports_vpn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='resultRoi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(blank=True, max_length=4, null=True)),
                ('roi_without_discount', models.FloatField()),
                ('roi_minimum', models.FloatField()),
                ('roi_maximum', models.FloatField()),
                ('roi_medium', models.FloatField()),
                ('create_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'waterproof_report_result_roi',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='calculatecostfunctionptap',
            name='function_plant',
        ),
    ]
