# Generated by Django 2.2.16 on 2021-03-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('element_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Element')),
                ('element_normalize_category', models.CharField(max_length=100, verbose_name='Name Element')),
                ('element_transported_water', models.CharField(max_length=100, verbose_name='Water Transported')),
                ('element_sediments_retained', models.CharField(max_length=100, verbose_name='Retrainer Sediments')),
                ('element_nitrogen_retained', models.CharField(max_length=100, verbose_name='Retrainer Nitrogen')),
                ('element_phosphorus_retained', models.CharField(max_length=100, verbose_name='Retrainer Phosphorus')),
                ('element_plant_id', models.IntegerField(verbose_name='Id Plant')),
                ('element_graph_id', models.IntegerField(verbose_name='Id Graph')),
                ('element_on_off', models.BooleanField(default=False, verbose_name='On off Element')),
                ('element_q_l', models.IntegerField(verbose_name='Q L Element')),
                ('element_awy', models.IntegerField(verbose_name='Awy Element')),
                ('element_cn_mg_l', models.IntegerField(verbose_name='CN Mg L Element')),
                ('element_cp_mg_l', models.IntegerField(verbose_name='CP Mg L Element')),
                ('element_csed_mg_l', models.IntegerField(verbose_name='Mg L Csed Element')),
                ('element_wn_kg', models.IntegerField(verbose_name='Wn Kg Element')),
                ('element_wn_rent_kg', models.IntegerField(verbose_name='Wn Rent Kg Element')),
                ('element_wp_rent_ton', models.IntegerField(verbose_name='Wn Rent Ton Element')),
                ('element_wsed_tom', models.IntegerField(verbose_name='Wsed Ton Element')),
                ('element_wp_kg', models.IntegerField(verbose_name='Wp Kg Element')),
                ('element_user', models.CharField(max_length=100, verbose_name='User Element')),
                ('element_date_create', models.DateTimeField(verbose_name='Date Create Element')),
                ('element_date_update', models.DateTimeField(auto_now=True, verbose_name='Date Update Element')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('plant_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Id Plant')),
                ('plant_name', models.CharField(max_length=100, verbose_name='Name Plant')),
                ('plant_description', models.CharField(max_length=300, verbose_name='Description Plant')),
                ('plant_suggest', models.CharField(max_length=1, verbose_name='Suggest Plant')),
                ('plant_user', models.CharField(max_length=100, verbose_name='User Plant')),
                ('plant_date_create', models.DateTimeField(verbose_name='Date Create Plant')),
                ('plant_date_update', models.DateTimeField(auto_now=True, verbose_name='Date Update Plant')),
            ],
        ),
    ]
