# Generated by Django 2.2.16 on 2021-01-26 14:17

from django.db import migrations, models
from django.utils.translation import ugettext_lazy as _

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('plant_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name=_('Id Plant'))),
                ('plant_name', models.CharField(max_length=100,verbose_name=_('Name Plant'))),
                ('plant_description', models.CharField(max_length=300,verbose_name=_('Description Plant'))),
                ('plant_suggest', models.CharField(max_length=1,verbose_name=_('Suggest Plant'))),
            ],
            options={
                'ordering': ['plant_id', 'plant_name'],
            },
        ),
    ]
