# Generated by Django 2.2.16 on 2021-03-29 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_parameters', '0003_auto_20210329_1316'),
        ('waterproof_treatment_plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csinfra',
            name='csinfra_id',
        ),
        migrations.RemoveField(
            model_name='csinfra',
            name='csinfra_plant_id',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_id',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_nitrogen_retained',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_phosphorus_retained',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_plant_id',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_sediments_retained',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_transported_water',
        ),
        migrations.RemoveField(
            model_name='element',
            name='element_wsed_ret_ton',
        ),
        migrations.RemoveField(
            model_name='function',
            name='function_id',
        ),
        migrations.RemoveField(
            model_name='function',
            name='function_plant_id',
        ),
        migrations.RemoveField(
            model_name='header',
            name='plant_city_id',
        ),
        migrations.RemoveField(
            model_name='header',
            name='plant_id',
        ),
        migrations.RemoveField(
            model_name='ptap',
            name='ptap_id',
        ),
        migrations.RemoveField(
            model_name='ptap',
            name='ptap_plant_id',
        ),
        migrations.AddField(
            model_name='csinfra',
            name='csinfra_plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Header'),
        ),
        migrations.AddField(
            model_name='csinfra',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='element_plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Header'),
        ),
        migrations.AddField(
            model_name='element',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='function',
            name='function_plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Header'),
        ),
        migrations.AddField(
            model_name='function',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='plant_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Cities'),
        ),
        migrations.AddField(
            model_name='ptap',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptap',
            name='ptap_plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_treatment_plants.Header'),
        ),
        migrations.AlterField(
            model_name='csinfra',
            name='csinfra_date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Create'),
        ),
        migrations.AlterField(
            model_name='csinfra',
            name='csinfra_date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Update'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Create Element'),
        ),
        migrations.AlterField(
            model_name='function',
            name='function_date_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Update'),
        ),
        migrations.AlterField(
            model_name='header',
            name='plant_date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Create Plant'),
        ),
        migrations.AlterField(
            model_name='ptap',
            name='ptap_date_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Update'),
        ),
    ]
