# Generated by Django 2.2.16 on 2021-03-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waterproof_parameters', '0002_managmentcosts_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_treatment_plants', '0001_initial'),
        ('waterproof_nbs_ca', '0001_initial'),
        ('waterproof_intake', '0003_auto_20210308_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('lucode', models.IntegerField(verbose_name='Lucode')),
                ('lulc_veg', models.BooleanField(null=True, verbose_name='LULC_veg')),
                ('root_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='root_depth')),
                ('kc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Kc')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Description')),
                ('default', models.BooleanField(verbose_name='Default')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('analysis_period_value', models.IntegerField(blank=True, null=True)),
                ('analysis_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('time_implement_portfolio', models.IntegerField(blank=True, null=True)),
                ('climate_scenario_portfolio', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_investment_scenario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('time_implement_investment_scenario', models.IntegerField(blank=True, null=True)),
                ('climate_investment_scenario', models.CharField(blank=True, max_length=100, null=True)),
                ('benefit_carbon_market', models.BooleanField(blank=True, null=True)),
                ('rellocated_remainder', models.BooleanField(blank=True, null=True)),
                ('cm_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cm_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Cities')),
                ('intakes', models.ManyToManyField(to='waterproof_intake.ElementSystem')),
                ('nbs', models.ManyToManyField(to='waterproof_nbs_ca.WaterproofNbsCa')),
                ('portfolios', models.ManyToManyField(to='waterproof_study_cases.Portfolio')),
                ('ptaps', models.ManyToManyField(to='waterproof_treatment_plants.Header')),
            ],
        ),
    ]
