# Generated by Django 2.2.16 on 2021-03-25 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waterproof_parameters', '0002_managmentcosts_discount'),
        ('waterproof_treatment_plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_nbs_ca', '0001_initial'),
        ('waterproof_intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('lucode', models.IntegerField(verbose_name='Lucode')),
                ('lulc_veg', models.BooleanField(null=True, verbose_name='LULC_veg')),
                ('root_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='root_depth')),
                ('kc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Kc')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Description')),
                ('default', models.BooleanField(verbose_name='Default')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('studycase_type', models.CharField(blank=True, max_length=10, null=True)),
                ('program_Director', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('implementation_Manager', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monitoring_Manager', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finance_Manager', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('administrative_Assistant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('office_Costs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overhead', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipment_Purchased', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicles_Purchased', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('equipment_Maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicle_Maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('discount_rate_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('discount_rate_minimunm', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('transaction_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('others', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contracts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('analysis_type', models.CharField(blank=True, max_length=10, null=True)),
                ('analysis_period_value', models.IntegerField(blank=True, null=True)),
                ('analysis_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
                ('time_implement', models.IntegerField(blank=True, null=True)),
                ('climate_scenario', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('benefit_carbon_market', models.BooleanField(blank=True, null=True)),
                ('rellocated_remainder', models.BooleanField(blank=True, null=True)),
                ('analysis_conservation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('analysis_active_restoration', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('analysis_passive_restoration', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('analysis_silvopastoral', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('analysis_agroforestry', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cm_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cm_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Cities')),
                ('intakes', models.ManyToManyField(to='waterproof_intake.ElementSystem')),
                ('nbs', models.ManyToManyField(to='waterproof_nbs_ca.WaterproofNbsCa')),
                ('portfolios', models.ManyToManyField(to='waterproof_study_cases.Portfolio')),
                ('ptaps', models.ManyToManyField(to='waterproof_treatment_plants.Header')),
            ],
        ),
    ]
