<<<<<<< HEAD
# Generated by Django 2.2.16 on 2021-03-03 17:23
=======
# Generated by Django 2.2.16 on 2021-03-04 17:02
>>>>>>> study_cases_jorge

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waterproof_parameters', '0001_initial'),
        ('waterproof_intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('lucode', models.IntegerField(verbose_name='Lucode')),
                ('lulc_veg', models.BooleanField(null=True, verbose_name='LULC_veg')),
                ('root_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='root_depth')),
                ('kc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Kc')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Description')),
                ('default', models.BooleanField(verbose_name='Default')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dws_name', models.CharField(max_length=100)),
                ('dws_description', models.CharField(max_length=500)),
                ('dws_analysis_period_value', models.IntegerField(blank=True, null=True)),
                ('dws_type_money', models.CharField(blank=True, max_length=10, null=True)),
                ('dws_benefit_function', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_id', models.IntegerField(blank=True, null=True)),
                ('dws_usr_create', models.IntegerField(blank=True, null=True)),
                ('dws_create_date', models.DateTimeField(blank=True, null=True)),
                ('dws_modif_date', models.DateTimeField(blank=True, null=True)),
                ('dws_rio_analysis_time', models.IntegerField(blank=True, null=True)),
                ('dws_time_implement_briefcase', models.IntegerField(blank=True, null=True)),
                ('dws_climate_scenario_briefcase', models.CharField(blank=True, max_length=100, null=True)),
                ('dws_annual_investment_scenario', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dws_time_implement_scenario', models.IntegerField(blank=True, null=True)),
                ('dws_climate_scenario_scenario', models.CharField(blank=True, max_length=100, null=True)),
                ('dws_authorization_case', models.CharField(blank=True, max_length=20, null=True)),
                ('dws_id_parent', models.IntegerField(blank=True, null=True)),
                ('dws_benefit_carbon_market', models.BooleanField(blank=True, null=True)),
                ('cm_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cm_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Cities')),
                ('dws_intakes', models.ManyToManyField(to='waterproof_intake.ElementSystem')),
                ('portfolios', models.ManyToManyField(to='waterproof_study_cases.Portfolio')),
            ],
        ),
    ]
