# Generated by Django 2.2.16 on 2021-04-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0001_initial'),
        ('waterproof_study_cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycases',
            name='analysis_active_restoration',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='analysis_agroforestry',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='analysis_conservation',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='analysis_passive_restoration',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='analysis_silvopastoral',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='nbs',
        ),
        migrations.CreateModel(
            name='StudyCases_NBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('nbs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.WaterproofNbsCa')),
                ('studycase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_study_cases.StudyCases')),
            ],
        ),
    ]
