# Generated by Django 2.2.16 on 2021-04-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waterproof_treatment_plants', '0001_initial'),
        ('waterproof_study_cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycases',
            name='ptaps',
            field=models.ManyToManyField(to='waterproof_treatment_plants.Header'),
        ),
    ]
