# Generated by Django 2.2.16 on 2021-03-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_treatment_plants', '0001_initial'),
        ('waterproof_study_cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_intakes',
            new_name='intakes',
        ),
        migrations.AddField(
            model_name='studycases',
            name='ptaps',
            field=models.ManyToManyField(to='waterproof_treatment_plants.Header'),
        ),
    ]
