# Generated by Django 2.2.16 on 2021-03-30 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycases',
            name='cm_city',
        ),
        migrations.AddField(
            model_name='studycases',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Cities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studycases',
            name='cm_currency',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='financial_currency',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='analysis_currency',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
