# Generated by Django 2.2.16 on 2021-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0002_auto_20210305_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_type_money',
            new_name='analysis_currency',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_analysis_period_value',
            new_name='analysis_period_value',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_annual_investment_scenario',
            new_name='annual_investment_scenario',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_benefit_carbon_market',
            new_name='benefit_carbon_market',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_benefit_function',
            new_name='climate_investment_scenario',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_climate_scenario_briefcase',
            new_name='climate_scenario_portfolio',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_create_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_modif_date',
            new_name='edit_date',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_id_parent',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_rio_analysis_time',
            new_name='time_implement_investment_scenario',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_time_implement_briefcase',
            new_name='time_implement_portfolio',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='dws_time_implement_scenario',
            new_name='usr_create',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='dws_authorization_case',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='dws_climate_scenario_scenario',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='dws_usr_create',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='estado_id',
        ),
        migrations.AddField(
            model_name='studycases',
            name='rellocated_remainder',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
