# Generated by Django 2.2.16 on 2021-05-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0003_studycases_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycases',
            name='is_run_analysis',
            field=models.BooleanField(default=False, verbose_name='Is run analysis'),
        ),
    ]
