# Generated by Django 2.2.16 on 2021-03-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_study_cases', '0003_auto_20210308_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycases',
            name='usr_create',
        ),
        migrations.AddField(
            model_name='studycases',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studycases',
            name='nbs',
            field=models.ManyToManyField(to='waterproof_nbs_ca.WaterproofNbsCa'),
        ),
    ]
