# Generated by Django 2.2.16 on 2021-02-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0003_auto_20210114_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studycases',
            options={},
        ),
    ]
