# Generated by Django 2.2.16 on 2021-03-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0004_auto_20210312_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycases',
            name='analysis_type',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='studycase_type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
