# Generated by Django 2.2.16 on 2021-05-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0004_auto_20210510_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycases_currency',
            name='description',
        ),
    ]
