# Generated by Django 2.2.16 on 2021-03-31 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0004_auto_20210331_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycases',
            name='climate_scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Climate_value'),
        ),
    ]
