# Generated by Django 2.2.16 on 2021-02-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0001_initial'),
        ('waterproof_study_cases', '0004_auto_20210208_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycases',
            name='ciudad_id',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='region_id',
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_climate_scenario_briefcase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='dws_intakes',
            field=models.ManyToManyField(to='waterproof_intake.Intake'),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_analysis_period_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_annual_investment_scenario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_authorization_case',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_benefit_carbon_market',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_benefit_function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_climate_scenario_scenario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_id_parent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_modif_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_rio_analysis_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_time_implement_briefcase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_time_implement_scenario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_type_money',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='dws_usr_create',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='estado_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='studycases',
            table=None,
        ),
    ]
