# Generated by Django 2.2.16 on 2021-03-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0005_auto_20210315_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycases',
            name='studycase_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
