# Generated by Django 2.2.16 on 2021-02-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0005_auto_20210208_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycases',
            name='dws_intakes',
            field=models.ManyToManyField(to='waterproof_intake.ElementSystem'),
        ),
    ]
