# Generated by Django 2.2.16 on 2021-02-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0006_auto_20210219_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Description')),
                ('default', models.BooleanField(verbose_name='Default')),
            ],
        ),
        migrations.AddField(
            model_name='studycases',
            name='portfolios',
            field=models.ManyToManyField(to='waterproof_study_cases.Portfolio'),
        ),
    ]
