# Generated by Django 2.2.16 on 2021-03-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0006_auto_20210315_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycases',
            name='Administrative_Assistant_USD_YEAR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Equipment_Maintenance_USD_YEAR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Equipment_Purchased_In_Year_1_USD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Finance_Manager_USD_YEAR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Implementation_Manager_USD_YEAR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Monitoring_and_Evaluation_Manager_USD_YEAR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Office_Costs_USD_YEAR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Overhead_USD_YEAR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Program_Director_USD_YEAR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Transaction_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Vehicle_Maintenance_USD_YEAR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='Vehicles_Purchased_In_Year_1_USD',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='drt_discount_rate_lower_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='drt_discount_rate_medium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='drt_discount_rate_upper_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
