# Generated by Django 2.2.16 on 2021-03-19 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0007_auto_20210319_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycases',
            old_name='Administrative_Assistant_USD_YEAR',
            new_name='administrative_Assistant',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='drt_discount_rate_lower_limit',
            new_name='discount_rate',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='drt_discount_rate_medium',
            new_name='discount_rate_maximum',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='drt_discount_rate_upper_limit',
            new_name='discount_rate_minimunm',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Equipment_Maintenance_USD_YEAR',
            new_name='equipment_Maintenance',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Equipment_Purchased_In_Year_1_USD',
            new_name='equipment_Purchased',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Finance_Manager_USD_YEAR',
            new_name='finance_Manager',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Implementation_Manager_USD_YEAR',
            new_name='implementation_Manager',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Monitoring_and_Evaluation_Manager_USD_YEAR',
            new_name='monitoring_Manager',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Office_Costs_USD_YEAR',
            new_name='office_Costs',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Overhead_USD_YEAR',
            new_name='overhead',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Program_Director_USD_YEAR',
            new_name='program_Director',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Vehicle_Maintenance_USD_YEAR',
            new_name='vehicle_Maintenance',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='Vehicles_Purchased_In_Year_1_USD',
            new_name='vehicles_Purchased',
        ),
    ]
