# Generated by Django 2.2.16 on 2021-02-19 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0030_auto_20210210_2310'),
        ('waterproof_study_cases', '0007_auto_20210219_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycases',
            name='cm_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.Currency'),
        ),
        migrations.AddField(
            model_name='studycases',
            name='cm_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
