# Generated by Django 2.2.16 on 2021-03-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0008_auto_20210319_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycases',
            old_name='Transaction_cost',
            new_name='others',
        ),
        migrations.AddField(
            model_name='studycases',
            name='transaction_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
