# Generated by Django 2.2.16 on 2021-02-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0008_auto_20210219_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('lucode', models.IntegerField(verbose_name='Lucode')),
                ('lulc_veg', models.BooleanField(null=True, verbose_name='LULC_veg')),
                ('root_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='root_depth')),
                ('kc', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Kc')),
            ],
        ),
    ]
