# Generated by Django 2.2.16 on 2021-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_treatment_plants', '0002_auto_20210303_1235'),
        ('waterproof_study_cases', '0009_modelparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycases',
            name='ptap',
            field=models.ManyToManyField(to='waterproof_treatment_plants.Header'),
        ),
    ]
