# Generated by Django 2.2.16 on 2021-03-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0009_auto_20210319_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycases',
            old_name='annual_investment_scenario',
            new_name='analysis_active_restoration',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='climate_investment_scenario',
            new_name='climate_scenario',
        ),
        migrations.RenameField(
            model_name='studycases',
            old_name='time_implement_investment_scenario',
            new_name='time_implement',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='climate_scenario_portfolio',
        ),
        migrations.RemoveField(
            model_name='studycases',
            name='time_implement_portfolio',
        ),
        migrations.AddField(
            model_name='studycases',
            name='analysis_agroforestry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='analysis_conservation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='analysis_passive_restoration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='analysis_silvopastoral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='studycases',
            name='annual_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='studycases',
            name='analysis_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
