version: '3.4'
x-common-django:
  image: waterproof/spcwaterproof:django-3.2
  environment: &id001
  - DEBUG=False
  volumes: &id002
  - ../../:/spcwaterproof/
  - ./_volume_static:/spcwaterproof-static/
  - ./_volume_media:/spcwaterproof-media/
services:
  django:
    image: waterproof/spcwaterproof:django-3.2
    environment: *id001
    volumes: *id002
    command: uwsgi --chdir=/spcwaterproof --module=geonode.wsgi --socket=:8000 --http=127.0.0.1:8001
      --master --processes=6 --threads=4 --buffer-size=32768 --listen=512 --harakiri=180
      --post-buffering=32768 --max-requests=5000 --reload-on-rss=2048 --worker-reload-mercy=90
      --socket-timeout=60
  celery:
    image: waterproof/spcwaterproof:django-3.2
    environment: *id001
    volumes: *id002
    command: celery -A geonode.celery_app:app worker --without-gossip --without-mingle
      -Ofair -B -E --statedb=/spcwaterproof-static/worker.state -s /spcwaterproof-static/celerybeat-schedule
      --loglevel=ERROR --concurrency=10 -n worker1@%h
  nginx:
    image: waterproof/spcwaterproof:nginx-3.2
    volumes:
    - ./_volume_static:/spcwaterproof-static/
    - ./_volume_media:/spcwaterproof-media/
    - ./_volume_certificates:/spcwaterproof-certificates/
    - /data/global_datasets/:/spcwaterproof-inputs/
    - /data/outputs/:/spcwaterproof-outputs/
  letsencrypt:
    image: waterproof/spcwaterproof:letsencrypt-3.2
    volumes:
    - ./_volume_certificates:/spcwaterproof-certificates/
  pgdumper_nogeo:
    image: waterproof/spcwaterproof:pgdumper-3.2
    volumes:
    - ./_volume_pgdumps:/spcwaterproof-pgdumps/
  pgdumper_geo:
    image: waterproof/spcwaterproof:pgdumper-3.2
    volumes:
    - ./_volume_pgdumps:/spcwaterproof-pgdumps/
  rclone:
    image: waterproof/spcwaterproof:rclone-3.2
    volumes:
    - ./_volume_pgdumps:/spcwaterproof-pgdumps/
    - ./_volume_media:/spcwaterproof-media/
    - ./_volume_geodatadir:/spcwaterproof-geodatadir/
  postgres:
    restart: on-failure
