# Generated by Django 2.2.16 on 2021-02-24 15:58

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waterproof_parameters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityShapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='RiosActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='RiosTransformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('unique_id', models.CharField(max_length=1024, verbose_name='Unique_id')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.RiosActivity')),
            ],
        ),
        migrations.CreateModel(
            name='RiosTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='WaterproofNbsCa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=2048, verbose_name='Description')),
                ('max_benefit_req_time', models.IntegerField(default=0, verbose_name='Time maximum benefit')),
                ('profit_pct_time_inter_assoc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percentage of benefit associated with interventions at time t=0')),
                ('unit_implementation_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit implementation costs (US $/ha)')),
                ('unit_maintenance_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit maintenance costs (US $/ha)')),
                ('periodicity_maitenance', models.IntegerField(default=0, verbose_name='Periodicity of maintenance (year)')),
                ('unit_oportunity_cost', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit oportunity costs (US $/ha)')),
                ('activity_shapefile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.ActivityShapefile')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countryField', to='waterproof_parameters.Countries')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencyField', to='waterproof_parameters.Countries')),
                ('rios_transformations', models.ManyToManyField(to='waterproof_nbs_ca.RiosTransformation')),
            ],
            options={
                'ordering': ['name', 'description'],
            },
        ),
        migrations.AddField(
            model_name='riosactivity',
            name='transition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_nbs_ca.RiosTransition'),
        ),
    ]
