# Generated by Django 2.2.16 on 2021-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterproofnbsca',
            name='slug',
            field=models.CharField(default='a', max_length=100, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
