# Generated by Django 2.2.16 on 2021-05-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0002_waterproofnbsca_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
