# Generated by Django 2.2.16 on 2021-08-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0003_auto_20210512_1743'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='waterproofnbsca',
        #     name='max_benefit_req_time',
        #     field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Time maximum benefit'),
        # ),
    ]
