# Generated by Django 2.2.16 on 2021-02-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0027_remove_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
