# Generated by Django 2.2.16 on 2021-02-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_nbs_ca', '0029_auto_20210210_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterproofnbsca',
            name='total_profits_sbn_consec_time',
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='profit_pct_time_inter_assoc',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percentage of benefit associated with interventions at time t=0'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_implementation_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit implementation costs (US $/ha)'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_maintenance_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit maintenance costs (US $/ha)'),
        ),
        migrations.AlterField(
            model_name='waterproofnbsca',
            name='unit_oportunity_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Unit oportunity costs (US $/ha)'),
        ),
    ]
