# Generated by Django 2.2.16 on 2021-03-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is complete'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='demand_parameters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.DemandParameters'),
        ),
        migrations.AlterField(
            model_name='intake',
            name='xml_graph',
            field=models.TextField(null=True, verbose_name='Graph'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='delimitation_type',
            field=models.CharField(max_length=30, null=True, verbose_name='Delimitation type'),
        ),
    ]
