# Generated by Django 2.2.16 on 2021-08-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0002_auto_20210503_2007'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='costfunctionsprocess',
        #     name='currency',
        #     field=models.CharField(max_length=255, null=True, verbose_name='Currency'),
        # ),
        # migrations.AddField(
        #     model_name='usercostfunctions',
        #     name='function_factor',
        #     field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='Factor'),
        # ),
    ]
