# Generated by Django 2.2.16 on 2021-05-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0002_auto_20210503_2007'),
        ('waterproof_intake', '0002_auto_20210505_0923'),
    ]

    operations = [
    ]
