# Generated by Django 2.2.16 on 2021-03-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0002_auto_20210308_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='intake',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Is complete'),
        ),
    ]
