# Generated by Django 2.2.16 on 2021-03-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_parameters', '0002_managmentcosts_discount'),
        ('waterproof_intake', '0003_auto_20210308_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogicalFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function1', models.TextField(verbose_name='Function1')),
                ('condition1', models.TextField(verbose_name='Condition1')),
                ('function2', models.TextField(verbose_name='Function2')),
                ('condition2', models.TextField(verbose_name='Condition2')),
                ('function3', models.TextField(verbose_name='Function3')),
                ('condition3', models.TextField(verbose_name='Condition3')),
            ],
        ),
        migrations.DeleteModel(
            name='SystemCosts',
        ),
        migrations.DeleteModel(
            name='UserCosts',
        ),
        migrations.AddField(
            model_name='usercostfunctions',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Countries'),
        ),
        migrations.AddField(
            model_name='usercostfunctions',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='usercostfunctions',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='usercostfunctions',
            name='function',
            field=models.TextField(blank=True, null=True, verbose_name='Function'),
        ),
        migrations.AlterField(
            model_name='usercostfunctions',
            name='template_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='waterproof_intake.CostFunctionsProcess'),
        ),
        migrations.AddField(
            model_name='userlogicalfunctions',
            name='mainFunction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.UserCostFunctions'),
        ),
    ]
