# Generated by Django 2.2.16 on 2021-03-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_intake', '0004_auto_20210317_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogicalfunctions',
            name='mainFunction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_intake.UserCostFunctions'),
        ),
    ]
