"""URLs for the waterproof fastflood module"""
from django.conf.urls import url
from django.urls import path
from . import views, api

urlpatterns = [
    path('', views.listWatershed, name='list-watershed'),
    path('create/', views.createWatershed, name='create-watershed'),    
    path('validateGeometry/', views.validateGeometry, name='valid-geometry-watershed'),
    path('view/<int:idx>', views.viewWatershed, name='view-watershed'),  
    path('edit/<int:idx>', views.editWatershed, name='edit-watershed'),  
    path('clone/<int:idx>', views.cloneWatershed, name='clone-watershed'),  
    path('delete/<int:idx>', views.deleteWatershed, name='delete-watershed'),
    path('watershedUsedByStudyCases/<int:idx>', api.watershedUsedByStudyCases), 
    path('watershedbycity/<int:id_city>/', api.getWatershedByCity, name='watershed-city'),
    path('watershed-by-id/<int:id>/', api.get_watershed_by_id, name='watershed-by-id'),
    path('save/', api.save, name='study_cases_fastflood_save'), 
    path('infoWatershed/<int:idx>', api.getInfoWatershedById, name='info-watershed'),
    path('watersheds', api.getWatersheds, name='watersheds'),
    path('bioByMacro/<int:watershed_id>', api.parametersBiophysicalByMacro, name='biophysical-macro'),
    path('bioById/<int:study_case_id>', api.parametersBiophysicalByStudyCase, name='biophysical-study-case'),
    path('damageInfo/<str:isoCountryValue>', api.getDamageInfoByCountry, name='damage-info'),
    path('parametersbycountry/<int:id_city>/', api.getParameterByCountry, name='parameters-country'),
    path('nbs/', api.getNBS, name='study_cases_fastflood_nbs'),
    path('currencys/', api.getStudyCaseCurrencys, name='currencys-study-cases'),
    path('exchangeRate/', api.getCurrencyExchange, name='exchange-rate-study-cases'),    
    path('savebio/', api.saveBiophysicals, name='fastflood_bio_save'),
    path('savedamage/', api.saveDamageData, name='fastflood_damage_save'),
    path('studyCase/', views.study_cases_list, name='fastflood_study_cases_list'),
    path('studyCase/create', views.create_study_case, name='create-fastflood-study-case'),
    path('studyCase/edit/<int:idx>', views.edit_study_case, name='edit-study-cases-fastFlood'),
    path('studyCase/clone/<int:idx>/<str:country_iso>', views.clone_study_case, name='clone-study-cases-fastFlood'),
    path('studyCase/view/<int:idx>', views.view_study_case, name='edit-study-cases-fastFlood'),
    path('studyCase/delete/<int:idx>', api.delete, name='delete-study-cases-fastFlood'),
    path('studyCase/public/<int:idx>', api.public, name='public-study-cases-fastFlood'),
    path('studyCase/private/<int:idx>', api.private, name='private-study-cases-fastFlood'),
    path('fastflood/run/', api.run, name='study_cases_run'),
    path('logsinfobyid/<int:id_study_case>/', api.getStudyCasesLogStatus, name='study_cases_log_status_fastflood'),
    path('getjson/', api.createJson, name='json_fastflood'),
    path('max-damage-cost/<str:countryIso>', api.getMaxDamageCostByCountry, name='max-damage-cost'),
    path('studycase-exist-by-name/', api.studycase_exist_by_name, name='studycase-exist-by-name'),
    path('watershed-exist-by-name/', api.watershed_exist_by_name, name='watershed-exist-by-name'),
    path('storm-durations/<int:watershed_id>/', api.get_storm_durations, name='get-storm-durations'),
]