# Generated by Django 3.0.5 on 2021-08-19 16:34

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Titulo')),
                ('titulo_en', models.CharField(max_length=300, verbose_name='Title')),
                ('resumen', models.TextField()),
                ('resumen_en', models.TextField(verbose_name='Resume (En)')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('contenido_en', ckeditor.fields.RichTextField()),
                ('publico', models.BooleanField(verbose_name='¿Publicado?')),
                ('imagen', models.ImageField(default='null', upload_to='articulos')),
                ('metadato_imagen', models.TextField()),
                ('metadato_imagen_en', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('nombre_en', models.CharField(max_length=300, verbose_name='Name')),
                ('descripcion', models.TextField(default='null', verbose_name='Descripcion')),
                ('descripcion_en', models.TextField(default='null', verbose_name='Description (En)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Referencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='Titulo')),
                ('anno', models.IntegerField(verbose_name='Año de publicación')),
                ('publicador', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('descripcion_en', models.TextField(verbose_name='Description (En)')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencies',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1300, verbose_name='URL')),
                ('descripcion', models.CharField(max_length=300, null=True, verbose_name='Descripcion')),
                ('descripcion_en', models.CharField(max_length=300, null=True, verbose_name='Description (En)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enlace', to='seccioneswiki.Article')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Links - URL',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='seccioneswiki.Category', verbose_name='Categorys'),
        ),
        migrations.AddField(
            model_name='article',
            name='referencies',
            field=models.ManyToManyField(blank=True, null=True, to='seccioneswiki.Referencies', verbose_name='Referencies'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
