# Generated by Django 2.2.16 on 2021-02-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('phonecode', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(max_length=255)),
                ('currency_symbol', models.CharField(max_length=255)),
                ('native', models.CharField(blank=True, max_length=255, null=True)),
                ('subregion', models.CharField(blank=True, max_length=255, null=True)),
                ('timezones', models.TextField(blank=True, null=True)),
                ('translations', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('emoji', models.CharField(blank=True, max_length=191, null=True)),
                ('emojiu', models.CharField(blank=True, db_column='emojiU', max_length=191, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('flag', models.BooleanField()),
                ('wikidataid', models.CharField(blank=True, db_column='wikiDataId', max_length=255, null=True)),
                ('global_multiplier_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('description_standard_spanish', models.CharField(blank=True, max_length=255, null=True)),
                ('description_standard_english', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_region_tnc', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Regions')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state_id', models.IntegerField()),
                ('state_code', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('created_at', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('flag', models.BooleanField()),
                ('wikidataid', models.CharField(blank=True, db_column='wikiDataId', max_length=255, null=True)),
                ('standard_name_spanish', models.CharField(max_length=255)),
                ('standard_name_english', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Countries')),
            ],
        ),
    ]
