# Generated by Django 2.2.16 on 2021-03-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagmentCosts_Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program_Director_USD_YEAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Implementation_Manager_USD_YEAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Monitoring_and_Evaluation_Manager_USD_YEAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Finance_Manager_USD_YEAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Administrative_Assistant_USD_YEAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Office_Costs_USD_YEAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Overhead_USD_YEAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Equipment_Purchased_In_Year_1_USD', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Vehicles_Purchased_In_Year_1_USD', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Equipment_Maintenance_USD_YEAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Vehicle_Maintenance_USD_YEAR', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('drt_discount_rate_medium', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('drt_discount_rate_upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('drt_discount_rate_lower_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('Transaction_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterproof_parameters.Countries')),
            ],
        ),
    ]
