# Generated by Django 2.2.16 on 2021-03-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_parameters', '0002_managmentcosts_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='managmentcosts_discount',
            name='drinking_water_standard_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='managmentcosts_discount',
            name='energy_multiplier_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='managmentcosts_discount',
            name='market_carbon_precing_USD_TonCO2e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='managmentcosts_discount',
            name='material_multiplier_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='managmentcosts_discount',
            name='work_hand_multiplier_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
