# Generated by Django 2.2.16 on 2021-05-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
       
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_study_cases', '0003_studycases_currency'),
        
    ]

    operations = [
       
        migrations.CreateModel(
            name='Countries_factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_USD', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=4)),
            ],
        ),
    ]
