# Generated by Django 2.2.16 on 2021-05-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_parameters', '0003_auto_20210329_1316'),
        ('waterproof_parameters', '0004_countries_factor_parameters_biophysical'),
    ]

    operations = [
    ]
