# Generated by Django 2.2.16 on 2021-05-07 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_parameters', '0005_merge_20210503_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries_factor',
            name='factor_USD',
        ),
        migrations.AddField(
            model_name='countries_factor',
            name='factor_EUR',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
       
    ]
