# Generated by Django 2.2.16 on 2021-05-07 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_study_cases', '0003_studycases_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waterproof_parameters', '0006_auto_20210507_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries_factor',
            name='factor_EUR',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=21, null=True),
        )
    ]
