# Generated by Django 2.2.16 on 2021-05-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterproof_parameters', '0007_auto_20210507_1715'),
        ('waterproof_parameters', '0004_parameters_biophysical'),
    ]

    operations = [
    ]
